-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR,
    MONTH(OS.SALES_DATE) MONTH,
    COUNT(DISTINCT OS.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID)/(SELECT COUNT(*) FROM USER_INFO UI WHERE YEAR(JOINED)=2021), 1) PUCHASED_RATIO
FROM ONLINE_SALE OS LEFT JOIN USER_INFO UI ON OS.USER_ID=UI.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;